config/routes.rb
Rails.application.routes.draw do
  resources :nginxes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nginx.rb
class Nginx < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nginxes_controller.rb
class NginxesController < ApplicationController
  before_action :set_nginx, only: %i[ show edit update destroy ]

  # GET /nginxes or /nginxes.json
  def index
    @nginxes = Nginx.all
  end

  # GET /nginxes/1 or /nginxes/1.json
  def show
  end

  # GET /nginxes/new
  def new
    @nginx = Nginx.new
  end

  # GET /nginxes/1/edit
  def edit
  end

  # POST /nginxes or /nginxes.json
  def create
    @nginx = Nginx.new(nginx_params)

    respond_to do |format|
      if @nginx.save
        format.html { redirect_to @nginx, notice: "Nginx was successfully created." }
        format.json { render :show, status: :created, location: @nginx }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @nginx.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nginxes/1 or /nginxes/1.json
  def update
    respond_to do |format|
      if @nginx.update(nginx_params)
        format.html { redirect_to @nginx, notice: "Nginx was successfully updated." }
        format.json { render :show, status: :ok, location: @nginx }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @nginx.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nginxes/1 or /nginxes/1.json
  def destroy
    @nginx.destroy
    respond_to do |format|
      format.html { redirect_to nginxes_url, notice: "Nginx was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nginx
      @nginx = Nginx.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def nginx_params
      params.require(:nginx).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nginxes_helper.rb
module NginxesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NginxApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nginxes/_form.html.erb
<%= form_with(model: nginx, local: true) do |form| %>
  <% if nginx.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nginx.errors.count, "error") %> prohibited this nginx from being saved:</h2>

      <ul>
      <% nginx.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nginxes/edit.html.erb
<h1>Editing Nginx</h1>

<%= render 'form', nginx: @nginx %>

<%= link_to 'Show', @nginx %> |
<%= link_to 'Back', nginxes_path %>

app/views/nginxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nginxes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nginxes.each do |nginx| %>
      <tr>
        <td><%= nginx.title %></td>
        <td><%= nginx.content %></td>
        <td><%= link_to 'Show', nginx %></td>
        <td><%= link_to 'Edit', edit_nginx_path(nginx) %></td>
        <td><%= link_to 'Destroy', nginx, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nginx', new_nginx_path %>

app/views/nginxes/new.html.erb
<h1>New Nginx</h1>

<%= render 'form', nginx: @nginx %>

<%= link_to 'Back', nginxes_path %>

app/views/nginxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @nginx.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @nginx.content %>
</p>

<%= link_to 'Edit', edit_nginx_path(@nginx) %> |
<%= link_to 'Back', nginxes_path %>